MAX_LABEL_LENGTH = 200
MAX_NAME_LENGTH = 300
MAX_DAYS = 14
MAX_MEALS_PER_DAY = 8
MAX_CATEGORIES_PER_MEAL = 20
MAX_OPTIONS_PER_CATEGORY = 50
MAX_AMOUNT = 100_000
MAX_POSITION = 10_000
MAX_OPTIONS = 2_000
MAX_BODY_BYTES = 1_048_576
POSTS_PER_HOUR = 3
INACTIVE_PLANS_KEPT = 1

BODY_TOO_LARGE_DETAIL = "The request body is larger than 1 MB."
RATE_LIMIT_DETAIL = "Too many diet plans were posted. Try again later."
